site_name: API Facade

nav:
  - Overview: ./index.md
  - Developer Environment: ./developer-environment.md
  - Code Architecture: ./code-architecture.md
  - Supporting Information: ./supporting-information.md
  - Convention: ./convention.md

plugins:
  - techdocs-core
