name: "Backend::Services::ApiFacade"

on:
  push:
    paths:
      - "backend/services/api-facade/**"
      - ".github/workflows/api-facade.yml"
    branches:
      - main
  pull_request:
    paths:
      - "backend/services/api-facade/**"
      - ".github/workflows/api-facade.yml"
    branches: "*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint and Build
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          yarn workspaces focus api-facade
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Load params
        run: |
          yarn load-params checking
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
