name: "Package::Backend::Common"

on:
  push:
    paths:
      - "packages/backend-common/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/backend-common/**"
    branches: '*'

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MY_SEMANTIC_RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.MY_SEMANTIC_RELEASE_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Lint and Build
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@andrew-org-test'
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          yarn install
          yarn nx lint @andrew-org-test/backend-common
          yarn nx build @andrew-org-test/backend-common
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          yarn nx release @andrew-org-test/backend-common
327311